# Generated by Django 4.2.4 on 2023-10-28 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(max_length=24, unique=True, verbose_name='Checksum')),
            ],
        ),
        migrations.CreateModel(
            name='ActionTaskState',
            fields=[
                ('taskresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_results.taskresult')),
                ('obj_id', models.PositiveIntegerField()),
                ('verbose_name', models.CharField(max_length=128, verbose_name='Verbose task name')),
                ('ctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            bases=('django_celery_results.taskresult',),
        ),
        migrations.CreateModel(
            name='ActionTaskNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[(10, 'debug'), (20, 'info'), (25, 'success'), (30, 'warning'), (40, 'error')], default='info', help_text='Level with which the message were added.', max_length=128, verbose_name='Message-level')),
                ('note', models.TextField(help_text='ActionTask note', verbose_name='Note')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='The datetime this message were added.', verbose_name='Time of creation')),
                ('action_task', models.ForeignKey(help_text='AktionTaskResult', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='async_actions.actiontaskstate', verbose_name='AktionTaskResult')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ('action_task', 'created_time'),
            },
        ),
        migrations.AddIndex(
            model_name='actiontaskstate',
            index=models.Index(fields=['obj_id'], name='async_actio_obj_id_878f73_idx'),
        ),
        migrations.AddIndex(
            model_name='actiontaskstate',
            index=models.Index(fields=['ctype'], name='async_actio_ctype_i_526e23_idx'),
        ),
    ]
