# Generated by Django 4.2.4 on 2023-08-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTaskResult',
            fields=[
                ('taskresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_results.taskresult')),
            ],
            bases=('django_celery_results.taskresult',),
        ),
    ]
