# Generated by Django 4.2.4 on 2023-09-13 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('async_actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTaskResult',
            fields=[
                ('taskresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_results.taskresult')),
                ('obj_id', models.PositiveIntegerField()),
                ('active', models.BooleanField(null=True)),
                ('ctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            bases=('django_celery_results.taskresult',),
        ),
        migrations.DeleteModel(
            name='ObjectTaskState',
        ),
        migrations.AddIndex(
            model_name='actiontaskresult',
            index=models.Index(fields=['obj_id'], name='async_actio_obj_id_ae2788_idx'),
        ),
        migrations.AddIndex(
            model_name='actiontaskresult',
            index=models.Index(fields=['ctype'], name='async_actio_ctype_i_589e3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='actiontaskresult',
            unique_together={('ctype', 'obj_id', 'active')},
        ),
    ]
