# Generated by Django 4.2.4 on 2023-09-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('async_actions', '0003_actiontasknote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActionTaskResult',
            new_name='ActionTaskState',
        ),
        migrations.RenameIndex(
            model_name='actiontaskstate',
            new_name='async_actio_obj_id_878f73_idx',
            old_name='async_actio_obj_id_ae2788_idx',
        ),
        migrations.RenameIndex(
            model_name='actiontaskstate',
            new_name='async_actio_ctype_i_526e23_idx',
            old_name='async_actio_ctype_i_589e3a_idx',
        ),
        migrations.AddIndex(
            model_name='actiontaskstate',
            index=models.Index(fields=['active'], name='async_actio_active_5f7c81_idx'),
        ),
    ]
