# Generated by Django 4.2.4 on 2023-09-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('async_actions', '0004_rename_actiontaskresult_actiontaskstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.BigIntegerField(unique=True, verbose_name='Lock-checksum')),
            ],
        ),
    ]
