# Generated by Django 4.2.4 on 2023-09-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('async_actions', '0005_lock'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='actiontaskstate',
            name='async_actio_active_5f7c81_idx',
        ),
        migrations.AlterUniqueTogether(
            name='actiontaskstate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='actiontaskstate',
            name='active',
        ),
    ]
